# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:

jobs:
  build:

    strategy:
      matrix:
        p1: [a, b, c, d, e]
        p2: [a, b, c, d, e]
        # p3: [a, b, c, d, e]
        node-version: [14.x, 16.x, 17.x, 18.x, 19.x]


    runs-on: ubuntu-latest
    name: p1 ${{ matrix.p1 }} p2 ${{ matrix.p3 }} Node ${{ matrix.node-version }} 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
